apiVersion: v1
kind: Service
metadata:
  name: "{NAME}-service"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "metrics"
    prometheus.io/port: "8080"
spec:
  selector:
    app: "{NAME}"
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: grpc
    port: 2345
    targetPort: grpc