apiVersion: v1
kind: Service
metadata:
  name: "{NAME}-service"
spec:
  selector:
    app: "{NAME}"
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: grpc
    port: 2345
    targetPort: grpc