apiVersion: v1
kind: Service
metadata:
  name: "{NAME}-service"
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: "{NAME}"
  ports:
  - name: http
    port: 80
    targetPort: http